// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 opcode = 1;</code>
   * @return The opcode.
   */
  int getOpcode();

  /**
   * <code>.tutorial.UserAccount account = 2;</code>
   * @return Whether the account field is set.
   */
  boolean hasAccount();
  /**
   * <code>.tutorial.UserAccount account = 2;</code>
   * @return The account.
   */
  com.p2p.p4f.protocols.UserAccount getAccount();
  /**
   * <code>.tutorial.UserAccount account = 2;</code>
   */
  com.p2p.p4f.protocols.UserAccountOrBuilder getAccountOrBuilder();

  public com.p2p.p4f.protocols.ClientMessage.ClientRequestsCase getClientRequestsCase();
}
