// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

public final class MessageWrapper {
  private MessageWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p4f_protocols_LoginInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p4f_protocols_LoginInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p4f_protocols_UserAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p4f_protocols_UserAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p4f_protocols_InfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p4f_protocols_InfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p4f_protocols_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p4f_protocols_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p4f_protocols_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p4f_protocols_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031PATH/MessageWrapper.proto\022\rp4f_protoco" +
      "ls\"/\n\tLoginInfo\022\020\n\010username\030\001 \001(\t\022\020\n\010pas" +
      "sword\030\002 \001(\t\"\\\n\013UserAccount\022\020\n\010username\030\001" +
      " \001(\t\022\014\n\004type\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022\r\n\005pho" +
      "ne\030\004 \001(\t\022\017\n\007address\030\005 \001(\t\"L\n\014InfoRespons" +
      "e\022\016\n\006reCode\030\001 \001(\005\022,\n\010userInfo\030\002 \001(\0132\032.p4" +
      "f_protocols.UserAccount\"_\n\rClientMessage" +
      "\022\016\n\006opcode\030\001 \001(\005\022+\n\007account\030\002 \001(\0132\030.p4f_" +
      "protocols.LoginInfoH\000B\021\n\017client_requests" +
      "\"h\n\rServerMessage\022\016\n\006opcode\030\001 \001(\005\0223\n\014inf" +
      "oResponse\030\002 \001(\0132\033.p4f_protocols.InfoResp" +
      "onseH\000B\022\n\020server_responsesB\031\n\025com.p2p.p4" +
      "f.protocolsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_p4f_protocols_LoginInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_p4f_protocols_LoginInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p4f_protocols_LoginInfo_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_p4f_protocols_UserAccount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_p4f_protocols_UserAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p4f_protocols_UserAccount_descriptor,
        new java.lang.String[] { "Username", "Type", "Email", "Phone", "Address", });
    internal_static_p4f_protocols_InfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_p4f_protocols_InfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p4f_protocols_InfoResponse_descriptor,
        new java.lang.String[] { "ReCode", "UserInfo", });
    internal_static_p4f_protocols_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_p4f_protocols_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p4f_protocols_ClientMessage_descriptor,
        new java.lang.String[] { "Opcode", "Account", "ClientRequests", });
    internal_static_p4f_protocols_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_p4f_protocols_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p4f_protocols_ServerMessage_descriptor,
        new java.lang.String[] { "Opcode", "InfoResponse", "ServerResponses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
