// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

public final class MessageWrapper {
  private MessageWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_UserAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_UserAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031PATH/MessageWrapper.proto\022\010tutorial\"1\n" +
      "\013UserAccount\022\020\n\010username\030\001 \001(\t\022\020\n\010passwo" +
      "rd\030\002 \001(\t\"\\\n\rClientMessage\022\016\n\006opcode\030\001 \001(" +
      "\005\022(\n\007account\030\002 \001(\0132\025.tutorial.UserAccoun" +
      "tH\000B\021\n\017client_requests\"J\n\rServerMessage\022" +
      "\016\n\006opcode\030\001 \001(\005\022\025\n\013loginResult\030\002 \001(\005H\000B\022" +
      "\n\020server_responsesB\031\n\025com.p2p.p4f.protoc" +
      "olsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_UserAccount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_UserAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_UserAccount_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_tutorial_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ClientMessage_descriptor,
        new java.lang.String[] { "Opcode", "Account", "ClientRequests", });
    internal_static_tutorial_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ServerMessage_descriptor,
        new java.lang.String[] { "Opcode", "LoginResult", "ServerResponses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
