// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

/**
 * Protobuf type {@code p4f_protocols.orderResponse}
 */
public final class orderResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:p4f_protocols.orderResponse)
    orderResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use orderResponse.newBuilder() to construct.
  private orderResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private orderResponse() {
    orderID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new orderResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private orderResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            orderID_ = s;
            break;
          }
          case 16: {

            orderResult_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_orderResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_orderResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.p2p.p4f.protocols.orderResponse.class, com.p2p.p4f.protocols.orderResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ORDERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object orderID_;
  /**
   * <pre>
   *orderID = username +_+ buyDate +_+ resID
   * </pre>
   *
   * <code>optional string orderID = 1;</code>
   * @return Whether the orderID field is set.
   */
  @java.lang.Override
  public boolean hasOrderID() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *orderID = username +_+ buyDate +_+ resID
   * </pre>
   *
   * <code>optional string orderID = 1;</code>
   * @return The orderID.
   */
  @java.lang.Override
  public java.lang.String getOrderID() {
    java.lang.Object ref = orderID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *orderID = username +_+ buyDate +_+ resID
   * </pre>
   *
   * <code>optional string orderID = 1;</code>
   * @return The bytes for orderID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrderIDBytes() {
    java.lang.Object ref = orderID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERRESULT_FIELD_NUMBER = 2;
  private int orderResult_;
  /**
   * <code>int32 orderResult = 2;</code>
   * @return The orderResult.
   */
  @java.lang.Override
  public int getOrderResult() {
    return orderResult_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderID_);
    }
    if (orderResult_ != 0) {
      output.writeInt32(2, orderResult_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderID_);
    }
    if (orderResult_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, orderResult_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.p2p.p4f.protocols.orderResponse)) {
      return super.equals(obj);
    }
    com.p2p.p4f.protocols.orderResponse other = (com.p2p.p4f.protocols.orderResponse) obj;

    if (hasOrderID() != other.hasOrderID()) return false;
    if (hasOrderID()) {
      if (!getOrderID()
          .equals(other.getOrderID())) return false;
    }
    if (getOrderResult()
        != other.getOrderResult()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOrderID()) {
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderID().hashCode();
    }
    hash = (37 * hash) + ORDERRESULT_FIELD_NUMBER;
    hash = (53 * hash) + getOrderResult();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.p2p.p4f.protocols.orderResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.orderResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.p2p.p4f.protocols.orderResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.p2p.p4f.protocols.orderResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.p2p.p4f.protocols.orderResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code p4f_protocols.orderResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:p4f_protocols.orderResponse)
      com.p2p.p4f.protocols.orderResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_orderResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_orderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.p2p.p4f.protocols.orderResponse.class, com.p2p.p4f.protocols.orderResponse.Builder.class);
    }

    // Construct using com.p2p.p4f.protocols.orderResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      orderID_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      orderResult_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_orderResponse_descriptor;
    }

    @java.lang.Override
    public com.p2p.p4f.protocols.orderResponse getDefaultInstanceForType() {
      return com.p2p.p4f.protocols.orderResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.p2p.p4f.protocols.orderResponse build() {
      com.p2p.p4f.protocols.orderResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.p2p.p4f.protocols.orderResponse buildPartial() {
      com.p2p.p4f.protocols.orderResponse result = new com.p2p.p4f.protocols.orderResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.orderID_ = orderID_;
      result.orderResult_ = orderResult_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.p2p.p4f.protocols.orderResponse) {
        return mergeFrom((com.p2p.p4f.protocols.orderResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.p2p.p4f.protocols.orderResponse other) {
      if (other == com.p2p.p4f.protocols.orderResponse.getDefaultInstance()) return this;
      if (other.hasOrderID()) {
        bitField0_ |= 0x00000001;
        orderID_ = other.orderID_;
        onChanged();
      }
      if (other.getOrderResult() != 0) {
        setOrderResult(other.getOrderResult());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.p2p.p4f.protocols.orderResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.p2p.p4f.protocols.orderResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object orderID_ = "";
    /**
     * <pre>
     *orderID = username +_+ buyDate +_+ resID
     * </pre>
     *
     * <code>optional string orderID = 1;</code>
     * @return Whether the orderID field is set.
     */
    public boolean hasOrderID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *orderID = username +_+ buyDate +_+ resID
     * </pre>
     *
     * <code>optional string orderID = 1;</code>
     * @return The orderID.
     */
    public java.lang.String getOrderID() {
      java.lang.Object ref = orderID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *orderID = username +_+ buyDate +_+ resID
     * </pre>
     *
     * <code>optional string orderID = 1;</code>
     * @return The bytes for orderID.
     */
    public com.google.protobuf.ByteString
        getOrderIDBytes() {
      java.lang.Object ref = orderID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *orderID = username +_+ buyDate +_+ resID
     * </pre>
     *
     * <code>optional string orderID = 1;</code>
     * @param value The orderID to set.
     * @return This builder for chaining.
     */
    public Builder setOrderID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      orderID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *orderID = username +_+ buyDate +_+ resID
     * </pre>
     *
     * <code>optional string orderID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      orderID_ = getDefaultInstance().getOrderID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *orderID = username +_+ buyDate +_+ resID
     * </pre>
     *
     * <code>optional string orderID = 1;</code>
     * @param value The bytes for orderID to set.
     * @return This builder for chaining.
     */
    public Builder setOrderIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      orderID_ = value;
      onChanged();
      return this;
    }

    private int orderResult_ ;
    /**
     * <code>int32 orderResult = 2;</code>
     * @return The orderResult.
     */
    @java.lang.Override
    public int getOrderResult() {
      return orderResult_;
    }
    /**
     * <code>int32 orderResult = 2;</code>
     * @param value The orderResult to set.
     * @return This builder for chaining.
     */
    public Builder setOrderResult(int value) {
      
      orderResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 orderResult = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderResult() {
      
      orderResult_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:p4f_protocols.orderResponse)
  }

  // @@protoc_insertion_point(class_scope:p4f_protocols.orderResponse)
  private static final com.p2p.p4f.protocols.orderResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.p2p.p4f.protocols.orderResponse();
  }

  public static com.p2p.p4f.protocols.orderResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<orderResponse>
      PARSER = new com.google.protobuf.AbstractParser<orderResponse>() {
    @java.lang.Override
    public orderResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new orderResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<orderResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<orderResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.p2p.p4f.protocols.orderResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

