// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p4f_protocols.ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 opcode = 1;</code>
   * @return The opcode.
   */
  int getOpcode();

  /**
   * <code>.p4f_protocols.InfoResponse loginResponse = 2;</code>
   * @return Whether the loginResponse field is set.
   */
  boolean hasLoginResponse();
  /**
   * <code>.p4f_protocols.InfoResponse loginResponse = 2;</code>
   * @return The loginResponse.
   */
  com.p2p.p4f.protocols.InfoResponse getLoginResponse();
  /**
   * <code>.p4f_protocols.InfoResponse loginResponse = 2;</code>
   */
  com.p2p.p4f.protocols.InfoResponseOrBuilder getLoginResponseOrBuilder();

  public com.p2p.p4f.protocols.ServerMessage.ServerResponsesCase getServerResponsesCase();
}
