// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 opcode = 1;</code>
   * @return The opcode.
   */
  int getOpcode();

  /**
   * <code>int32 loginResult = 2;</code>
   * @return Whether the loginResult field is set.
   */
  boolean hasLoginResult();
  /**
   * <code>int32 loginResult = 2;</code>
   * @return The loginResult.
   */
  int getLoginResult();

  public com.p2p.p4f.protocols.ServerMessage.ServerResponsesCase getServerResponsesCase();
}
