// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

/**
 * Protobuf type {@code p4f_protocols.ServerMessage}
 */
public final class ServerMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:p4f_protocols.ServerMessage)
    ServerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerMessage.newBuilder() to construct.
  private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            opcode_ = input.readInt32();
            break;
          }
          case 18: {
            com.p2p.p4f.protocols.InfoResponse.Builder subBuilder = null;
            if (serverResponsesCase_ == 2) {
              subBuilder = ((com.p2p.p4f.protocols.InfoResponse) serverResponses_).toBuilder();
            }
            serverResponses_ =
                input.readMessage(com.p2p.p4f.protocols.InfoResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.p2p.p4f.protocols.InfoResponse) serverResponses_);
              serverResponses_ = subBuilder.buildPartial();
            }
            serverResponsesCase_ = 2;
            break;
          }
          case 24: {
            serverResponsesCase_ = 3;
            serverResponses_ = input.readInt32();
            break;
          }
          case 34: {
            com.p2p.p4f.protocols.orderResponse.Builder subBuilder = null;
            if (serverResponsesCase_ == 4) {
              subBuilder = ((com.p2p.p4f.protocols.orderResponse) serverResponses_).toBuilder();
            }
            serverResponses_ =
                input.readMessage(com.p2p.p4f.protocols.orderResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.p2p.p4f.protocols.orderResponse) serverResponses_);
              serverResponses_ = subBuilder.buildPartial();
            }
            serverResponsesCase_ = 4;
            break;
          }
          case 42: {
            com.p2p.p4f.protocols.changePassInfo.Builder subBuilder = null;
            if (serverResponsesCase_ == 5) {
              subBuilder = ((com.p2p.p4f.protocols.changePassInfo) serverResponses_).toBuilder();
            }
            serverResponses_ =
                input.readMessage(com.p2p.p4f.protocols.changePassInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.p2p.p4f.protocols.changePassInfo) serverResponses_);
              serverResponses_ = subBuilder.buildPartial();
            }
            serverResponsesCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_ServerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_ServerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.p2p.p4f.protocols.ServerMessage.class, com.p2p.p4f.protocols.ServerMessage.Builder.class);
  }

  private int serverResponsesCase_ = 0;
  private java.lang.Object serverResponses_;
  public enum ServerResponsesCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INFORESPONSE(2),
    RESPONSECODE(3),
    ORDERRES(4),
    CHANGERES(5),
    SERVERRESPONSES_NOT_SET(0);
    private final int value;
    private ServerResponsesCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServerResponsesCase valueOf(int value) {
      return forNumber(value);
    }

    public static ServerResponsesCase forNumber(int value) {
      switch (value) {
        case 2: return INFORESPONSE;
        case 3: return RESPONSECODE;
        case 4: return ORDERRES;
        case 5: return CHANGERES;
        case 0: return SERVERRESPONSES_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ServerResponsesCase
  getServerResponsesCase() {
    return ServerResponsesCase.forNumber(
        serverResponsesCase_);
  }

  public static final int OPCODE_FIELD_NUMBER = 1;
  private int opcode_;
  /**
   * <code>int32 opcode = 1;</code>
   * @return The opcode.
   */
  @java.lang.Override
  public int getOpcode() {
    return opcode_;
  }

  public static final int INFORESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
   * @return Whether the infoResponse field is set.
   */
  @java.lang.Override
  public boolean hasInfoResponse() {
    return serverResponsesCase_ == 2;
  }
  /**
   * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
   * @return The infoResponse.
   */
  @java.lang.Override
  public com.p2p.p4f.protocols.InfoResponse getInfoResponse() {
    if (serverResponsesCase_ == 2) {
       return (com.p2p.p4f.protocols.InfoResponse) serverResponses_;
    }
    return com.p2p.p4f.protocols.InfoResponse.getDefaultInstance();
  }
  /**
   * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
   */
  @java.lang.Override
  public com.p2p.p4f.protocols.InfoResponseOrBuilder getInfoResponseOrBuilder() {
    if (serverResponsesCase_ == 2) {
       return (com.p2p.p4f.protocols.InfoResponse) serverResponses_;
    }
    return com.p2p.p4f.protocols.InfoResponse.getDefaultInstance();
  }

  public static final int RESPONSECODE_FIELD_NUMBER = 3;
  /**
   * <pre>
   *Announce Register status and change password status
   * </pre>
   *
   * <code>int32 responseCode = 3;</code>
   * @return Whether the responseCode field is set.
   */
  @java.lang.Override
  public boolean hasResponseCode() {
    return serverResponsesCase_ == 3;
  }
  /**
   * <pre>
   *Announce Register status and change password status
   * </pre>
   *
   * <code>int32 responseCode = 3;</code>
   * @return The responseCode.
   */
  @java.lang.Override
  public int getResponseCode() {
    if (serverResponsesCase_ == 3) {
      return (java.lang.Integer) serverResponses_;
    }
    return 0;
  }

  public static final int ORDERRES_FIELD_NUMBER = 4;
  /**
   * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
   * @return Whether the orderRes field is set.
   */
  @java.lang.Override
  public boolean hasOrderRes() {
    return serverResponsesCase_ == 4;
  }
  /**
   * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
   * @return The orderRes.
   */
  @java.lang.Override
  public com.p2p.p4f.protocols.orderResponse getOrderRes() {
    if (serverResponsesCase_ == 4) {
       return (com.p2p.p4f.protocols.orderResponse) serverResponses_;
    }
    return com.p2p.p4f.protocols.orderResponse.getDefaultInstance();
  }
  /**
   * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
   */
  @java.lang.Override
  public com.p2p.p4f.protocols.orderResponseOrBuilder getOrderResOrBuilder() {
    if (serverResponsesCase_ == 4) {
       return (com.p2p.p4f.protocols.orderResponse) serverResponses_;
    }
    return com.p2p.p4f.protocols.orderResponse.getDefaultInstance();
  }

  public static final int CHANGERES_FIELD_NUMBER = 5;
  /**
   * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
   * @return Whether the changeRes field is set.
   */
  @java.lang.Override
  public boolean hasChangeRes() {
    return serverResponsesCase_ == 5;
  }
  /**
   * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
   * @return The changeRes.
   */
  @java.lang.Override
  public com.p2p.p4f.protocols.changePassInfo getChangeRes() {
    if (serverResponsesCase_ == 5) {
       return (com.p2p.p4f.protocols.changePassInfo) serverResponses_;
    }
    return com.p2p.p4f.protocols.changePassInfo.getDefaultInstance();
  }
  /**
   * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
   */
  @java.lang.Override
  public com.p2p.p4f.protocols.changePassInfoOrBuilder getChangeResOrBuilder() {
    if (serverResponsesCase_ == 5) {
       return (com.p2p.p4f.protocols.changePassInfo) serverResponses_;
    }
    return com.p2p.p4f.protocols.changePassInfo.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (opcode_ != 0) {
      output.writeInt32(1, opcode_);
    }
    if (serverResponsesCase_ == 2) {
      output.writeMessage(2, (com.p2p.p4f.protocols.InfoResponse) serverResponses_);
    }
    if (serverResponsesCase_ == 3) {
      output.writeInt32(
          3, (int)((java.lang.Integer) serverResponses_));
    }
    if (serverResponsesCase_ == 4) {
      output.writeMessage(4, (com.p2p.p4f.protocols.orderResponse) serverResponses_);
    }
    if (serverResponsesCase_ == 5) {
      output.writeMessage(5, (com.p2p.p4f.protocols.changePassInfo) serverResponses_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (opcode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, opcode_);
    }
    if (serverResponsesCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.p2p.p4f.protocols.InfoResponse) serverResponses_);
    }
    if (serverResponsesCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            3, (int)((java.lang.Integer) serverResponses_));
    }
    if (serverResponsesCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.p2p.p4f.protocols.orderResponse) serverResponses_);
    }
    if (serverResponsesCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.p2p.p4f.protocols.changePassInfo) serverResponses_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.p2p.p4f.protocols.ServerMessage)) {
      return super.equals(obj);
    }
    com.p2p.p4f.protocols.ServerMessage other = (com.p2p.p4f.protocols.ServerMessage) obj;

    if (getOpcode()
        != other.getOpcode()) return false;
    if (!getServerResponsesCase().equals(other.getServerResponsesCase())) return false;
    switch (serverResponsesCase_) {
      case 2:
        if (!getInfoResponse()
            .equals(other.getInfoResponse())) return false;
        break;
      case 3:
        if (getResponseCode()
            != other.getResponseCode()) return false;
        break;
      case 4:
        if (!getOrderRes()
            .equals(other.getOrderRes())) return false;
        break;
      case 5:
        if (!getChangeRes()
            .equals(other.getChangeRes())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPCODE_FIELD_NUMBER;
    hash = (53 * hash) + getOpcode();
    switch (serverResponsesCase_) {
      case 2:
        hash = (37 * hash) + INFORESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getInfoResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
        hash = (53 * hash) + getResponseCode();
        break;
      case 4:
        hash = (37 * hash) + ORDERRES_FIELD_NUMBER;
        hash = (53 * hash) + getOrderRes().hashCode();
        break;
      case 5:
        hash = (37 * hash) + CHANGERES_FIELD_NUMBER;
        hash = (53 * hash) + getChangeRes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.p2p.p4f.protocols.ServerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.p2p.p4f.protocols.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.p2p.p4f.protocols.ServerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code p4f_protocols.ServerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:p4f_protocols.ServerMessage)
      com.p2p.p4f.protocols.ServerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_ServerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.p2p.p4f.protocols.ServerMessage.class, com.p2p.p4f.protocols.ServerMessage.Builder.class);
    }

    // Construct using com.p2p.p4f.protocols.ServerMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      opcode_ = 0;

      serverResponsesCase_ = 0;
      serverResponses_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.p2p.p4f.protocols.MessageWrapper.internal_static_p4f_protocols_ServerMessage_descriptor;
    }

    @java.lang.Override
    public com.p2p.p4f.protocols.ServerMessage getDefaultInstanceForType() {
      return com.p2p.p4f.protocols.ServerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.p2p.p4f.protocols.ServerMessage build() {
      com.p2p.p4f.protocols.ServerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.p2p.p4f.protocols.ServerMessage buildPartial() {
      com.p2p.p4f.protocols.ServerMessage result = new com.p2p.p4f.protocols.ServerMessage(this);
      result.opcode_ = opcode_;
      if (serverResponsesCase_ == 2) {
        if (infoResponseBuilder_ == null) {
          result.serverResponses_ = serverResponses_;
        } else {
          result.serverResponses_ = infoResponseBuilder_.build();
        }
      }
      if (serverResponsesCase_ == 3) {
        result.serverResponses_ = serverResponses_;
      }
      if (serverResponsesCase_ == 4) {
        if (orderResBuilder_ == null) {
          result.serverResponses_ = serverResponses_;
        } else {
          result.serverResponses_ = orderResBuilder_.build();
        }
      }
      if (serverResponsesCase_ == 5) {
        if (changeResBuilder_ == null) {
          result.serverResponses_ = serverResponses_;
        } else {
          result.serverResponses_ = changeResBuilder_.build();
        }
      }
      result.serverResponsesCase_ = serverResponsesCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.p2p.p4f.protocols.ServerMessage) {
        return mergeFrom((com.p2p.p4f.protocols.ServerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.p2p.p4f.protocols.ServerMessage other) {
      if (other == com.p2p.p4f.protocols.ServerMessage.getDefaultInstance()) return this;
      if (other.getOpcode() != 0) {
        setOpcode(other.getOpcode());
      }
      switch (other.getServerResponsesCase()) {
        case INFORESPONSE: {
          mergeInfoResponse(other.getInfoResponse());
          break;
        }
        case RESPONSECODE: {
          setResponseCode(other.getResponseCode());
          break;
        }
        case ORDERRES: {
          mergeOrderRes(other.getOrderRes());
          break;
        }
        case CHANGERES: {
          mergeChangeRes(other.getChangeRes());
          break;
        }
        case SERVERRESPONSES_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.p2p.p4f.protocols.ServerMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.p2p.p4f.protocols.ServerMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int serverResponsesCase_ = 0;
    private java.lang.Object serverResponses_;
    public ServerResponsesCase
        getServerResponsesCase() {
      return ServerResponsesCase.forNumber(
          serverResponsesCase_);
    }

    public Builder clearServerResponses() {
      serverResponsesCase_ = 0;
      serverResponses_ = null;
      onChanged();
      return this;
    }


    private int opcode_ ;
    /**
     * <code>int32 opcode = 1;</code>
     * @return The opcode.
     */
    @java.lang.Override
    public int getOpcode() {
      return opcode_;
    }
    /**
     * <code>int32 opcode = 1;</code>
     * @param value The opcode to set.
     * @return This builder for chaining.
     */
    public Builder setOpcode(int value) {
      
      opcode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 opcode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpcode() {
      
      opcode_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.p2p.p4f.protocols.InfoResponse, com.p2p.p4f.protocols.InfoResponse.Builder, com.p2p.p4f.protocols.InfoResponseOrBuilder> infoResponseBuilder_;
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     * @return Whether the infoResponse field is set.
     */
    @java.lang.Override
    public boolean hasInfoResponse() {
      return serverResponsesCase_ == 2;
    }
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     * @return The infoResponse.
     */
    @java.lang.Override
    public com.p2p.p4f.protocols.InfoResponse getInfoResponse() {
      if (infoResponseBuilder_ == null) {
        if (serverResponsesCase_ == 2) {
          return (com.p2p.p4f.protocols.InfoResponse) serverResponses_;
        }
        return com.p2p.p4f.protocols.InfoResponse.getDefaultInstance();
      } else {
        if (serverResponsesCase_ == 2) {
          return infoResponseBuilder_.getMessage();
        }
        return com.p2p.p4f.protocols.InfoResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     */
    public Builder setInfoResponse(com.p2p.p4f.protocols.InfoResponse value) {
      if (infoResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serverResponses_ = value;
        onChanged();
      } else {
        infoResponseBuilder_.setMessage(value);
      }
      serverResponsesCase_ = 2;
      return this;
    }
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     */
    public Builder setInfoResponse(
        com.p2p.p4f.protocols.InfoResponse.Builder builderForValue) {
      if (infoResponseBuilder_ == null) {
        serverResponses_ = builderForValue.build();
        onChanged();
      } else {
        infoResponseBuilder_.setMessage(builderForValue.build());
      }
      serverResponsesCase_ = 2;
      return this;
    }
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     */
    public Builder mergeInfoResponse(com.p2p.p4f.protocols.InfoResponse value) {
      if (infoResponseBuilder_ == null) {
        if (serverResponsesCase_ == 2 &&
            serverResponses_ != com.p2p.p4f.protocols.InfoResponse.getDefaultInstance()) {
          serverResponses_ = com.p2p.p4f.protocols.InfoResponse.newBuilder((com.p2p.p4f.protocols.InfoResponse) serverResponses_)
              .mergeFrom(value).buildPartial();
        } else {
          serverResponses_ = value;
        }
        onChanged();
      } else {
        if (serverResponsesCase_ == 2) {
          infoResponseBuilder_.mergeFrom(value);
        }
        infoResponseBuilder_.setMessage(value);
      }
      serverResponsesCase_ = 2;
      return this;
    }
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     */
    public Builder clearInfoResponse() {
      if (infoResponseBuilder_ == null) {
        if (serverResponsesCase_ == 2) {
          serverResponsesCase_ = 0;
          serverResponses_ = null;
          onChanged();
        }
      } else {
        if (serverResponsesCase_ == 2) {
          serverResponsesCase_ = 0;
          serverResponses_ = null;
        }
        infoResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     */
    public com.p2p.p4f.protocols.InfoResponse.Builder getInfoResponseBuilder() {
      return getInfoResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     */
    @java.lang.Override
    public com.p2p.p4f.protocols.InfoResponseOrBuilder getInfoResponseOrBuilder() {
      if ((serverResponsesCase_ == 2) && (infoResponseBuilder_ != null)) {
        return infoResponseBuilder_.getMessageOrBuilder();
      } else {
        if (serverResponsesCase_ == 2) {
          return (com.p2p.p4f.protocols.InfoResponse) serverResponses_;
        }
        return com.p2p.p4f.protocols.InfoResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.p2p.p4f.protocols.InfoResponse, com.p2p.p4f.protocols.InfoResponse.Builder, com.p2p.p4f.protocols.InfoResponseOrBuilder> 
        getInfoResponseFieldBuilder() {
      if (infoResponseBuilder_ == null) {
        if (!(serverResponsesCase_ == 2)) {
          serverResponses_ = com.p2p.p4f.protocols.InfoResponse.getDefaultInstance();
        }
        infoResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.p2p.p4f.protocols.InfoResponse, com.p2p.p4f.protocols.InfoResponse.Builder, com.p2p.p4f.protocols.InfoResponseOrBuilder>(
                (com.p2p.p4f.protocols.InfoResponse) serverResponses_,
                getParentForChildren(),
                isClean());
        serverResponses_ = null;
      }
      serverResponsesCase_ = 2;
      onChanged();;
      return infoResponseBuilder_;
    }

    /**
     * <pre>
     *Announce Register status and change password status
     * </pre>
     *
     * <code>int32 responseCode = 3;</code>
     * @return Whether the responseCode field is set.
     */
    public boolean hasResponseCode() {
      return serverResponsesCase_ == 3;
    }
    /**
     * <pre>
     *Announce Register status and change password status
     * </pre>
     *
     * <code>int32 responseCode = 3;</code>
     * @return The responseCode.
     */
    public int getResponseCode() {
      if (serverResponsesCase_ == 3) {
        return (java.lang.Integer) serverResponses_;
      }
      return 0;
    }
    /**
     * <pre>
     *Announce Register status and change password status
     * </pre>
     *
     * <code>int32 responseCode = 3;</code>
     * @param value The responseCode to set.
     * @return This builder for chaining.
     */
    public Builder setResponseCode(int value) {
      serverResponsesCase_ = 3;
      serverResponses_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Announce Register status and change password status
     * </pre>
     *
     * <code>int32 responseCode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseCode() {
      if (serverResponsesCase_ == 3) {
        serverResponsesCase_ = 0;
        serverResponses_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.p2p.p4f.protocols.orderResponse, com.p2p.p4f.protocols.orderResponse.Builder, com.p2p.p4f.protocols.orderResponseOrBuilder> orderResBuilder_;
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     * @return Whether the orderRes field is set.
     */
    @java.lang.Override
    public boolean hasOrderRes() {
      return serverResponsesCase_ == 4;
    }
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     * @return The orderRes.
     */
    @java.lang.Override
    public com.p2p.p4f.protocols.orderResponse getOrderRes() {
      if (orderResBuilder_ == null) {
        if (serverResponsesCase_ == 4) {
          return (com.p2p.p4f.protocols.orderResponse) serverResponses_;
        }
        return com.p2p.p4f.protocols.orderResponse.getDefaultInstance();
      } else {
        if (serverResponsesCase_ == 4) {
          return orderResBuilder_.getMessage();
        }
        return com.p2p.p4f.protocols.orderResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     */
    public Builder setOrderRes(com.p2p.p4f.protocols.orderResponse value) {
      if (orderResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serverResponses_ = value;
        onChanged();
      } else {
        orderResBuilder_.setMessage(value);
      }
      serverResponsesCase_ = 4;
      return this;
    }
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     */
    public Builder setOrderRes(
        com.p2p.p4f.protocols.orderResponse.Builder builderForValue) {
      if (orderResBuilder_ == null) {
        serverResponses_ = builderForValue.build();
        onChanged();
      } else {
        orderResBuilder_.setMessage(builderForValue.build());
      }
      serverResponsesCase_ = 4;
      return this;
    }
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     */
    public Builder mergeOrderRes(com.p2p.p4f.protocols.orderResponse value) {
      if (orderResBuilder_ == null) {
        if (serverResponsesCase_ == 4 &&
            serverResponses_ != com.p2p.p4f.protocols.orderResponse.getDefaultInstance()) {
          serverResponses_ = com.p2p.p4f.protocols.orderResponse.newBuilder((com.p2p.p4f.protocols.orderResponse) serverResponses_)
              .mergeFrom(value).buildPartial();
        } else {
          serverResponses_ = value;
        }
        onChanged();
      } else {
        if (serverResponsesCase_ == 4) {
          orderResBuilder_.mergeFrom(value);
        }
        orderResBuilder_.setMessage(value);
      }
      serverResponsesCase_ = 4;
      return this;
    }
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     */
    public Builder clearOrderRes() {
      if (orderResBuilder_ == null) {
        if (serverResponsesCase_ == 4) {
          serverResponsesCase_ = 0;
          serverResponses_ = null;
          onChanged();
        }
      } else {
        if (serverResponsesCase_ == 4) {
          serverResponsesCase_ = 0;
          serverResponses_ = null;
        }
        orderResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     */
    public com.p2p.p4f.protocols.orderResponse.Builder getOrderResBuilder() {
      return getOrderResFieldBuilder().getBuilder();
    }
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     */
    @java.lang.Override
    public com.p2p.p4f.protocols.orderResponseOrBuilder getOrderResOrBuilder() {
      if ((serverResponsesCase_ == 4) && (orderResBuilder_ != null)) {
        return orderResBuilder_.getMessageOrBuilder();
      } else {
        if (serverResponsesCase_ == 4) {
          return (com.p2p.p4f.protocols.orderResponse) serverResponses_;
        }
        return com.p2p.p4f.protocols.orderResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.orderResponse orderRes = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.p2p.p4f.protocols.orderResponse, com.p2p.p4f.protocols.orderResponse.Builder, com.p2p.p4f.protocols.orderResponseOrBuilder> 
        getOrderResFieldBuilder() {
      if (orderResBuilder_ == null) {
        if (!(serverResponsesCase_ == 4)) {
          serverResponses_ = com.p2p.p4f.protocols.orderResponse.getDefaultInstance();
        }
        orderResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.p2p.p4f.protocols.orderResponse, com.p2p.p4f.protocols.orderResponse.Builder, com.p2p.p4f.protocols.orderResponseOrBuilder>(
                (com.p2p.p4f.protocols.orderResponse) serverResponses_,
                getParentForChildren(),
                isClean());
        serverResponses_ = null;
      }
      serverResponsesCase_ = 4;
      onChanged();;
      return orderResBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.p2p.p4f.protocols.changePassInfo, com.p2p.p4f.protocols.changePassInfo.Builder, com.p2p.p4f.protocols.changePassInfoOrBuilder> changeResBuilder_;
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     * @return Whether the changeRes field is set.
     */
    @java.lang.Override
    public boolean hasChangeRes() {
      return serverResponsesCase_ == 5;
    }
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     * @return The changeRes.
     */
    @java.lang.Override
    public com.p2p.p4f.protocols.changePassInfo getChangeRes() {
      if (changeResBuilder_ == null) {
        if (serverResponsesCase_ == 5) {
          return (com.p2p.p4f.protocols.changePassInfo) serverResponses_;
        }
        return com.p2p.p4f.protocols.changePassInfo.getDefaultInstance();
      } else {
        if (serverResponsesCase_ == 5) {
          return changeResBuilder_.getMessage();
        }
        return com.p2p.p4f.protocols.changePassInfo.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     */
    public Builder setChangeRes(com.p2p.p4f.protocols.changePassInfo value) {
      if (changeResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serverResponses_ = value;
        onChanged();
      } else {
        changeResBuilder_.setMessage(value);
      }
      serverResponsesCase_ = 5;
      return this;
    }
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     */
    public Builder setChangeRes(
        com.p2p.p4f.protocols.changePassInfo.Builder builderForValue) {
      if (changeResBuilder_ == null) {
        serverResponses_ = builderForValue.build();
        onChanged();
      } else {
        changeResBuilder_.setMessage(builderForValue.build());
      }
      serverResponsesCase_ = 5;
      return this;
    }
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     */
    public Builder mergeChangeRes(com.p2p.p4f.protocols.changePassInfo value) {
      if (changeResBuilder_ == null) {
        if (serverResponsesCase_ == 5 &&
            serverResponses_ != com.p2p.p4f.protocols.changePassInfo.getDefaultInstance()) {
          serverResponses_ = com.p2p.p4f.protocols.changePassInfo.newBuilder((com.p2p.p4f.protocols.changePassInfo) serverResponses_)
              .mergeFrom(value).buildPartial();
        } else {
          serverResponses_ = value;
        }
        onChanged();
      } else {
        if (serverResponsesCase_ == 5) {
          changeResBuilder_.mergeFrom(value);
        }
        changeResBuilder_.setMessage(value);
      }
      serverResponsesCase_ = 5;
      return this;
    }
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     */
    public Builder clearChangeRes() {
      if (changeResBuilder_ == null) {
        if (serverResponsesCase_ == 5) {
          serverResponsesCase_ = 0;
          serverResponses_ = null;
          onChanged();
        }
      } else {
        if (serverResponsesCase_ == 5) {
          serverResponsesCase_ = 0;
          serverResponses_ = null;
        }
        changeResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     */
    public com.p2p.p4f.protocols.changePassInfo.Builder getChangeResBuilder() {
      return getChangeResFieldBuilder().getBuilder();
    }
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     */
    @java.lang.Override
    public com.p2p.p4f.protocols.changePassInfoOrBuilder getChangeResOrBuilder() {
      if ((serverResponsesCase_ == 5) && (changeResBuilder_ != null)) {
        return changeResBuilder_.getMessageOrBuilder();
      } else {
        if (serverResponsesCase_ == 5) {
          return (com.p2p.p4f.protocols.changePassInfo) serverResponses_;
        }
        return com.p2p.p4f.protocols.changePassInfo.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.changePassInfo changeRes = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.p2p.p4f.protocols.changePassInfo, com.p2p.p4f.protocols.changePassInfo.Builder, com.p2p.p4f.protocols.changePassInfoOrBuilder> 
        getChangeResFieldBuilder() {
      if (changeResBuilder_ == null) {
        if (!(serverResponsesCase_ == 5)) {
          serverResponses_ = com.p2p.p4f.protocols.changePassInfo.getDefaultInstance();
        }
        changeResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.p2p.p4f.protocols.changePassInfo, com.p2p.p4f.protocols.changePassInfo.Builder, com.p2p.p4f.protocols.changePassInfoOrBuilder>(
                (com.p2p.p4f.protocols.changePassInfo) serverResponses_,
                getParentForChildren(),
                isClean());
        serverResponses_ = null;
      }
      serverResponsesCase_ = 5;
      onChanged();;
      return changeResBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:p4f_protocols.ServerMessage)
  }

  // @@protoc_insertion_point(class_scope:p4f_protocols.ServerMessage)
  private static final com.p2p.p4f.protocols.ServerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.p2p.p4f.protocols.ServerMessage();
  }

  public static com.p2p.p4f.protocols.ServerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerMessage>
      PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
    @java.lang.Override
    public ServerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.p2p.p4f.protocols.ServerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

