// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.p4f_project.protocols;

/**
 * <pre>
 *op: 0 = Logout, 1 = Login, 2 = register, 3 = change password;
 * </pre>
 *
 * Protobuf type {@code p4f_protocols.ClientMessage}
 */
public final class ClientMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:p4f_protocols.ClientMessage)
    ClientMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientMessage.newBuilder() to construct.
  private ClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            opcode_ = input.readInt32();
            break;
          }
          case 18: {
            com.example.p4f_project.protocols.LoginInfo.Builder subBuilder = null;
            if (clientRequestsCase_ == 2) {
              subBuilder = ((com.example.p4f_project.protocols.LoginInfo) clientRequests_).toBuilder();
            }
            clientRequests_ =
                input.readMessage(com.example.p4f_project.protocols.LoginInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.example.p4f_project.protocols.LoginInfo) clientRequests_);
              clientRequests_ = subBuilder.buildPartial();
            }
            clientRequestsCase_ = 2;
            break;
          }
          case 26: {
            com.example.p4f_project.protocols.RegisterInfo.Builder subBuilder = null;
            if (clientRequestsCase_ == 3) {
              subBuilder = ((com.example.p4f_project.protocols.RegisterInfo) clientRequests_).toBuilder();
            }
            clientRequests_ =
                input.readMessage(com.example.p4f_project.protocols.RegisterInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.example.p4f_project.protocols.RegisterInfo) clientRequests_);
              clientRequests_ = subBuilder.buildPartial();
            }
            clientRequestsCase_ = 3;
            break;
          }
          case 34: {
            com.example.p4f_project.protocols.Order.Builder subBuilder = null;
            if (clientRequestsCase_ == 4) {
              subBuilder = ((com.example.p4f_project.protocols.Order) clientRequests_).toBuilder();
            }
            clientRequests_ =
                input.readMessage(com.example.p4f_project.protocols.Order.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.example.p4f_project.protocols.Order) clientRequests_);
              clientRequests_ = subBuilder.buildPartial();
            }
            clientRequestsCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_ClientMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_ClientMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.p4f_project.protocols.ClientMessage.class, com.example.p4f_project.protocols.ClientMessage.Builder.class);
  }

  private int clientRequestsCase_ = 0;
  private java.lang.Object clientRequests_;
  public enum ClientRequestsCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ACCOUNT(2),
    REGACC(3),
    ORDER(4),
    CLIENTREQUESTS_NOT_SET(0);
    private final int value;
    private ClientRequestsCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClientRequestsCase valueOf(int value) {
      return forNumber(value);
    }

    public static ClientRequestsCase forNumber(int value) {
      switch (value) {
        case 2: return ACCOUNT;
        case 3: return REGACC;
        case 4: return ORDER;
        case 0: return CLIENTREQUESTS_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ClientRequestsCase
  getClientRequestsCase() {
    return ClientRequestsCase.forNumber(
        clientRequestsCase_);
  }

  public static final int OPCODE_FIELD_NUMBER = 1;
  private int opcode_;
  /**
   * <code>int32 opcode = 1;</code>
   * @return The opcode.
   */
  @java.lang.Override
  public int getOpcode() {
    return opcode_;
  }

  public static final int ACCOUNT_FIELD_NUMBER = 2;
  /**
   * <pre>
   *Use for login and change password
   * </pre>
   *
   * <code>.p4f_protocols.LoginInfo account = 2;</code>
   * @return Whether the account field is set.
   */
  @java.lang.Override
  public boolean hasAccount() {
    return clientRequestsCase_ == 2;
  }
  /**
   * <pre>
   *Use for login and change password
   * </pre>
   *
   * <code>.p4f_protocols.LoginInfo account = 2;</code>
   * @return The account.
   */
  @java.lang.Override
  public com.example.p4f_project.protocols.LoginInfo getAccount() {
    if (clientRequestsCase_ == 2) {
       return (com.example.p4f_project.protocols.LoginInfo) clientRequests_;
    }
    return com.example.p4f_project.protocols.LoginInfo.getDefaultInstance();
  }
  /**
   * <pre>
   *Use for login and change password
   * </pre>
   *
   * <code>.p4f_protocols.LoginInfo account = 2;</code>
   */
  @java.lang.Override
  public com.example.p4f_project.protocols.LoginInfoOrBuilder getAccountOrBuilder() {
    if (clientRequestsCase_ == 2) {
       return (com.example.p4f_project.protocols.LoginInfo) clientRequests_;
    }
    return com.example.p4f_project.protocols.LoginInfo.getDefaultInstance();
  }

  public static final int REGACC_FIELD_NUMBER = 3;
  /**
   * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
   * @return Whether the regAcc field is set.
   */
  @java.lang.Override
  public boolean hasRegAcc() {
    return clientRequestsCase_ == 3;
  }
  /**
   * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
   * @return The regAcc.
   */
  @java.lang.Override
  public com.example.p4f_project.protocols.RegisterInfo getRegAcc() {
    if (clientRequestsCase_ == 3) {
       return (com.example.p4f_project.protocols.RegisterInfo) clientRequests_;
    }
    return com.example.p4f_project.protocols.RegisterInfo.getDefaultInstance();
  }
  /**
   * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
   */
  @java.lang.Override
  public com.example.p4f_project.protocols.RegisterInfoOrBuilder getRegAccOrBuilder() {
    if (clientRequestsCase_ == 3) {
       return (com.example.p4f_project.protocols.RegisterInfo) clientRequests_;
    }
    return com.example.p4f_project.protocols.RegisterInfo.getDefaultInstance();
  }

  public static final int ORDER_FIELD_NUMBER = 4;
  /**
   * <code>.p4f_protocols.Order order = 4;</code>
   * @return Whether the order field is set.
   */
  @java.lang.Override
  public boolean hasOrder() {
    return clientRequestsCase_ == 4;
  }
  /**
   * <code>.p4f_protocols.Order order = 4;</code>
   * @return The order.
   */
  @java.lang.Override
  public com.example.p4f_project.protocols.Order getOrder() {
    if (clientRequestsCase_ == 4) {
       return (com.example.p4f_project.protocols.Order) clientRequests_;
    }
    return com.example.p4f_project.protocols.Order.getDefaultInstance();
  }
  /**
   * <code>.p4f_protocols.Order order = 4;</code>
   */
  @java.lang.Override
  public com.example.p4f_project.protocols.OrderOrBuilder getOrderOrBuilder() {
    if (clientRequestsCase_ == 4) {
       return (com.example.p4f_project.protocols.Order) clientRequests_;
    }
    return com.example.p4f_project.protocols.Order.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (opcode_ != 0) {
      output.writeInt32(1, opcode_);
    }
    if (clientRequestsCase_ == 2) {
      output.writeMessage(2, (com.example.p4f_project.protocols.LoginInfo) clientRequests_);
    }
    if (clientRequestsCase_ == 3) {
      output.writeMessage(3, (com.example.p4f_project.protocols.RegisterInfo) clientRequests_);
    }
    if (clientRequestsCase_ == 4) {
      output.writeMessage(4, (com.example.p4f_project.protocols.Order) clientRequests_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (opcode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, opcode_);
    }
    if (clientRequestsCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.example.p4f_project.protocols.LoginInfo) clientRequests_);
    }
    if (clientRequestsCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.example.p4f_project.protocols.RegisterInfo) clientRequests_);
    }
    if (clientRequestsCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.example.p4f_project.protocols.Order) clientRequests_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.p4f_project.protocols.ClientMessage)) {
      return super.equals(obj);
    }
    com.example.p4f_project.protocols.ClientMessage other = (com.example.p4f_project.protocols.ClientMessage) obj;

    if (getOpcode()
        != other.getOpcode()) return false;
    if (!getClientRequestsCase().equals(other.getClientRequestsCase())) return false;
    switch (clientRequestsCase_) {
      case 2:
        if (!getAccount()
            .equals(other.getAccount())) return false;
        break;
      case 3:
        if (!getRegAcc()
            .equals(other.getRegAcc())) return false;
        break;
      case 4:
        if (!getOrder()
            .equals(other.getOrder())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPCODE_FIELD_NUMBER;
    hash = (53 * hash) + getOpcode();
    switch (clientRequestsCase_) {
      case 2:
        hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAccount().hashCode();
        break;
      case 3:
        hash = (37 * hash) + REGACC_FIELD_NUMBER;
        hash = (53 * hash) + getRegAcc().hashCode();
        break;
      case 4:
        hash = (37 * hash) + ORDER_FIELD_NUMBER;
        hash = (53 * hash) + getOrder().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.p4f_project.protocols.ClientMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.p4f_project.protocols.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.p4f_project.protocols.ClientMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *op: 0 = Logout, 1 = Login, 2 = register, 3 = change password;
   * </pre>
   *
   * Protobuf type {@code p4f_protocols.ClientMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:p4f_protocols.ClientMessage)
      com.example.p4f_project.protocols.ClientMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_ClientMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.p4f_project.protocols.ClientMessage.class, com.example.p4f_project.protocols.ClientMessage.Builder.class);
    }

    // Construct using com.example.p4f_project.protocols.ClientMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      opcode_ = 0;

      clientRequestsCase_ = 0;
      clientRequests_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_ClientMessage_descriptor;
    }

    @java.lang.Override
    public com.example.p4f_project.protocols.ClientMessage getDefaultInstanceForType() {
      return com.example.p4f_project.protocols.ClientMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.p4f_project.protocols.ClientMessage build() {
      com.example.p4f_project.protocols.ClientMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.p4f_project.protocols.ClientMessage buildPartial() {
      com.example.p4f_project.protocols.ClientMessage result = new com.example.p4f_project.protocols.ClientMessage(this);
      result.opcode_ = opcode_;
      if (clientRequestsCase_ == 2) {
        if (accountBuilder_ == null) {
          result.clientRequests_ = clientRequests_;
        } else {
          result.clientRequests_ = accountBuilder_.build();
        }
      }
      if (clientRequestsCase_ == 3) {
        if (regAccBuilder_ == null) {
          result.clientRequests_ = clientRequests_;
        } else {
          result.clientRequests_ = regAccBuilder_.build();
        }
      }
      if (clientRequestsCase_ == 4) {
        if (orderBuilder_ == null) {
          result.clientRequests_ = clientRequests_;
        } else {
          result.clientRequests_ = orderBuilder_.build();
        }
      }
      result.clientRequestsCase_ = clientRequestsCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.p4f_project.protocols.ClientMessage) {
        return mergeFrom((com.example.p4f_project.protocols.ClientMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.p4f_project.protocols.ClientMessage other) {
      if (other == com.example.p4f_project.protocols.ClientMessage.getDefaultInstance()) return this;
      if (other.getOpcode() != 0) {
        setOpcode(other.getOpcode());
      }
      switch (other.getClientRequestsCase()) {
        case ACCOUNT: {
          mergeAccount(other.getAccount());
          break;
        }
        case REGACC: {
          mergeRegAcc(other.getRegAcc());
          break;
        }
        case ORDER: {
          mergeOrder(other.getOrder());
          break;
        }
        case CLIENTREQUESTS_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.p4f_project.protocols.ClientMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.p4f_project.protocols.ClientMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int clientRequestsCase_ = 0;
    private java.lang.Object clientRequests_;
    public ClientRequestsCase
        getClientRequestsCase() {
      return ClientRequestsCase.forNumber(
          clientRequestsCase_);
    }

    public Builder clearClientRequests() {
      clientRequestsCase_ = 0;
      clientRequests_ = null;
      onChanged();
      return this;
    }


    private int opcode_ ;
    /**
     * <code>int32 opcode = 1;</code>
     * @return The opcode.
     */
    @java.lang.Override
    public int getOpcode() {
      return opcode_;
    }
    /**
     * <code>int32 opcode = 1;</code>
     * @param value The opcode to set.
     * @return This builder for chaining.
     */
    public Builder setOpcode(int value) {
      
      opcode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 opcode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpcode() {
      
      opcode_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.p4f_project.protocols.LoginInfo, com.example.p4f_project.protocols.LoginInfo.Builder, com.example.p4f_project.protocols.LoginInfoOrBuilder> accountBuilder_;
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     * @return Whether the account field is set.
     */
    @java.lang.Override
    public boolean hasAccount() {
      return clientRequestsCase_ == 2;
    }
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     * @return The account.
     */
    @java.lang.Override
    public com.example.p4f_project.protocols.LoginInfo getAccount() {
      if (accountBuilder_ == null) {
        if (clientRequestsCase_ == 2) {
          return (com.example.p4f_project.protocols.LoginInfo) clientRequests_;
        }
        return com.example.p4f_project.protocols.LoginInfo.getDefaultInstance();
      } else {
        if (clientRequestsCase_ == 2) {
          return accountBuilder_.getMessage();
        }
        return com.example.p4f_project.protocols.LoginInfo.getDefaultInstance();
      }
    }
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     */
    public Builder setAccount(com.example.p4f_project.protocols.LoginInfo value) {
      if (accountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientRequests_ = value;
        onChanged();
      } else {
        accountBuilder_.setMessage(value);
      }
      clientRequestsCase_ = 2;
      return this;
    }
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     */
    public Builder setAccount(
        com.example.p4f_project.protocols.LoginInfo.Builder builderForValue) {
      if (accountBuilder_ == null) {
        clientRequests_ = builderForValue.build();
        onChanged();
      } else {
        accountBuilder_.setMessage(builderForValue.build());
      }
      clientRequestsCase_ = 2;
      return this;
    }
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     */
    public Builder mergeAccount(com.example.p4f_project.protocols.LoginInfo value) {
      if (accountBuilder_ == null) {
        if (clientRequestsCase_ == 2 &&
            clientRequests_ != com.example.p4f_project.protocols.LoginInfo.getDefaultInstance()) {
          clientRequests_ = com.example.p4f_project.protocols.LoginInfo.newBuilder((com.example.p4f_project.protocols.LoginInfo) clientRequests_)
              .mergeFrom(value).buildPartial();
        } else {
          clientRequests_ = value;
        }
        onChanged();
      } else {
        if (clientRequestsCase_ == 2) {
          accountBuilder_.mergeFrom(value);
        }
        accountBuilder_.setMessage(value);
      }
      clientRequestsCase_ = 2;
      return this;
    }
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     */
    public Builder clearAccount() {
      if (accountBuilder_ == null) {
        if (clientRequestsCase_ == 2) {
          clientRequestsCase_ = 0;
          clientRequests_ = null;
          onChanged();
        }
      } else {
        if (clientRequestsCase_ == 2) {
          clientRequestsCase_ = 0;
          clientRequests_ = null;
        }
        accountBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     */
    public com.example.p4f_project.protocols.LoginInfo.Builder getAccountBuilder() {
      return getAccountFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     */
    @java.lang.Override
    public com.example.p4f_project.protocols.LoginInfoOrBuilder getAccountOrBuilder() {
      if ((clientRequestsCase_ == 2) && (accountBuilder_ != null)) {
        return accountBuilder_.getMessageOrBuilder();
      } else {
        if (clientRequestsCase_ == 2) {
          return (com.example.p4f_project.protocols.LoginInfo) clientRequests_;
        }
        return com.example.p4f_project.protocols.LoginInfo.getDefaultInstance();
      }
    }
    /**
     * <pre>
     *Use for login and change password
     * </pre>
     *
     * <code>.p4f_protocols.LoginInfo account = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.p4f_project.protocols.LoginInfo, com.example.p4f_project.protocols.LoginInfo.Builder, com.example.p4f_project.protocols.LoginInfoOrBuilder> 
        getAccountFieldBuilder() {
      if (accountBuilder_ == null) {
        if (!(clientRequestsCase_ == 2)) {
          clientRequests_ = com.example.p4f_project.protocols.LoginInfo.getDefaultInstance();
        }
        accountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.p4f_project.protocols.LoginInfo, com.example.p4f_project.protocols.LoginInfo.Builder, com.example.p4f_project.protocols.LoginInfoOrBuilder>(
                (com.example.p4f_project.protocols.LoginInfo) clientRequests_,
                getParentForChildren(),
                isClean());
        clientRequests_ = null;
      }
      clientRequestsCase_ = 2;
      onChanged();;
      return accountBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.p4f_project.protocols.RegisterInfo, com.example.p4f_project.protocols.RegisterInfo.Builder, com.example.p4f_project.protocols.RegisterInfoOrBuilder> regAccBuilder_;
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     * @return Whether the regAcc field is set.
     */
    @java.lang.Override
    public boolean hasRegAcc() {
      return clientRequestsCase_ == 3;
    }
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     * @return The regAcc.
     */
    @java.lang.Override
    public com.example.p4f_project.protocols.RegisterInfo getRegAcc() {
      if (regAccBuilder_ == null) {
        if (clientRequestsCase_ == 3) {
          return (com.example.p4f_project.protocols.RegisterInfo) clientRequests_;
        }
        return com.example.p4f_project.protocols.RegisterInfo.getDefaultInstance();
      } else {
        if (clientRequestsCase_ == 3) {
          return regAccBuilder_.getMessage();
        }
        return com.example.p4f_project.protocols.RegisterInfo.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     */
    public Builder setRegAcc(com.example.p4f_project.protocols.RegisterInfo value) {
      if (regAccBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientRequests_ = value;
        onChanged();
      } else {
        regAccBuilder_.setMessage(value);
      }
      clientRequestsCase_ = 3;
      return this;
    }
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     */
    public Builder setRegAcc(
        com.example.p4f_project.protocols.RegisterInfo.Builder builderForValue) {
      if (regAccBuilder_ == null) {
        clientRequests_ = builderForValue.build();
        onChanged();
      } else {
        regAccBuilder_.setMessage(builderForValue.build());
      }
      clientRequestsCase_ = 3;
      return this;
    }
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     */
    public Builder mergeRegAcc(com.example.p4f_project.protocols.RegisterInfo value) {
      if (regAccBuilder_ == null) {
        if (clientRequestsCase_ == 3 &&
            clientRequests_ != com.example.p4f_project.protocols.RegisterInfo.getDefaultInstance()) {
          clientRequests_ = com.example.p4f_project.protocols.RegisterInfo.newBuilder((com.example.p4f_project.protocols.RegisterInfo) clientRequests_)
              .mergeFrom(value).buildPartial();
        } else {
          clientRequests_ = value;
        }
        onChanged();
      } else {
        if (clientRequestsCase_ == 3) {
          regAccBuilder_.mergeFrom(value);
        }
        regAccBuilder_.setMessage(value);
      }
      clientRequestsCase_ = 3;
      return this;
    }
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     */
    public Builder clearRegAcc() {
      if (regAccBuilder_ == null) {
        if (clientRequestsCase_ == 3) {
          clientRequestsCase_ = 0;
          clientRequests_ = null;
          onChanged();
        }
      } else {
        if (clientRequestsCase_ == 3) {
          clientRequestsCase_ = 0;
          clientRequests_ = null;
        }
        regAccBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     */
    public com.example.p4f_project.protocols.RegisterInfo.Builder getRegAccBuilder() {
      return getRegAccFieldBuilder().getBuilder();
    }
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     */
    @java.lang.Override
    public com.example.p4f_project.protocols.RegisterInfoOrBuilder getRegAccOrBuilder() {
      if ((clientRequestsCase_ == 3) && (regAccBuilder_ != null)) {
        return regAccBuilder_.getMessageOrBuilder();
      } else {
        if (clientRequestsCase_ == 3) {
          return (com.example.p4f_project.protocols.RegisterInfo) clientRequests_;
        }
        return com.example.p4f_project.protocols.RegisterInfo.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.RegisterInfo regAcc = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.p4f_project.protocols.RegisterInfo, com.example.p4f_project.protocols.RegisterInfo.Builder, com.example.p4f_project.protocols.RegisterInfoOrBuilder> 
        getRegAccFieldBuilder() {
      if (regAccBuilder_ == null) {
        if (!(clientRequestsCase_ == 3)) {
          clientRequests_ = com.example.p4f_project.protocols.RegisterInfo.getDefaultInstance();
        }
        regAccBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.p4f_project.protocols.RegisterInfo, com.example.p4f_project.protocols.RegisterInfo.Builder, com.example.p4f_project.protocols.RegisterInfoOrBuilder>(
                (com.example.p4f_project.protocols.RegisterInfo) clientRequests_,
                getParentForChildren(),
                isClean());
        clientRequests_ = null;
      }
      clientRequestsCase_ = 3;
      onChanged();;
      return regAccBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.p4f_project.protocols.Order, com.example.p4f_project.protocols.Order.Builder, com.example.p4f_project.protocols.OrderOrBuilder> orderBuilder_;
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     * @return Whether the order field is set.
     */
    @java.lang.Override
    public boolean hasOrder() {
      return clientRequestsCase_ == 4;
    }
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     * @return The order.
     */
    @java.lang.Override
    public com.example.p4f_project.protocols.Order getOrder() {
      if (orderBuilder_ == null) {
        if (clientRequestsCase_ == 4) {
          return (com.example.p4f_project.protocols.Order) clientRequests_;
        }
        return com.example.p4f_project.protocols.Order.getDefaultInstance();
      } else {
        if (clientRequestsCase_ == 4) {
          return orderBuilder_.getMessage();
        }
        return com.example.p4f_project.protocols.Order.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     */
    public Builder setOrder(com.example.p4f_project.protocols.Order value) {
      if (orderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientRequests_ = value;
        onChanged();
      } else {
        orderBuilder_.setMessage(value);
      }
      clientRequestsCase_ = 4;
      return this;
    }
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     */
    public Builder setOrder(
        com.example.p4f_project.protocols.Order.Builder builderForValue) {
      if (orderBuilder_ == null) {
        clientRequests_ = builderForValue.build();
        onChanged();
      } else {
        orderBuilder_.setMessage(builderForValue.build());
      }
      clientRequestsCase_ = 4;
      return this;
    }
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     */
    public Builder mergeOrder(com.example.p4f_project.protocols.Order value) {
      if (orderBuilder_ == null) {
        if (clientRequestsCase_ == 4 &&
            clientRequests_ != com.example.p4f_project.protocols.Order.getDefaultInstance()) {
          clientRequests_ = com.example.p4f_project.protocols.Order.newBuilder((com.example.p4f_project.protocols.Order) clientRequests_)
              .mergeFrom(value).buildPartial();
        } else {
          clientRequests_ = value;
        }
        onChanged();
      } else {
        if (clientRequestsCase_ == 4) {
          orderBuilder_.mergeFrom(value);
        }
        orderBuilder_.setMessage(value);
      }
      clientRequestsCase_ = 4;
      return this;
    }
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     */
    public Builder clearOrder() {
      if (orderBuilder_ == null) {
        if (clientRequestsCase_ == 4) {
          clientRequestsCase_ = 0;
          clientRequests_ = null;
          onChanged();
        }
      } else {
        if (clientRequestsCase_ == 4) {
          clientRequestsCase_ = 0;
          clientRequests_ = null;
        }
        orderBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     */
    public com.example.p4f_project.protocols.Order.Builder getOrderBuilder() {
      return getOrderFieldBuilder().getBuilder();
    }
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     */
    @java.lang.Override
    public com.example.p4f_project.protocols.OrderOrBuilder getOrderOrBuilder() {
      if ((clientRequestsCase_ == 4) && (orderBuilder_ != null)) {
        return orderBuilder_.getMessageOrBuilder();
      } else {
        if (clientRequestsCase_ == 4) {
          return (com.example.p4f_project.protocols.Order) clientRequests_;
        }
        return com.example.p4f_project.protocols.Order.getDefaultInstance();
      }
    }
    /**
     * <code>.p4f_protocols.Order order = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.p4f_project.protocols.Order, com.example.p4f_project.protocols.Order.Builder, com.example.p4f_project.protocols.OrderOrBuilder> 
        getOrderFieldBuilder() {
      if (orderBuilder_ == null) {
        if (!(clientRequestsCase_ == 4)) {
          clientRequests_ = com.example.p4f_project.protocols.Order.getDefaultInstance();
        }
        orderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.p4f_project.protocols.Order, com.example.p4f_project.protocols.Order.Builder, com.example.p4f_project.protocols.OrderOrBuilder>(
                (com.example.p4f_project.protocols.Order) clientRequests_,
                getParentForChildren(),
                isClean());
        clientRequests_ = null;
      }
      clientRequestsCase_ = 4;
      onChanged();;
      return orderBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:p4f_protocols.ClientMessage)
  }

  // @@protoc_insertion_point(class_scope:p4f_protocols.ClientMessage)
  private static final com.example.p4f_project.protocols.ClientMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.p4f_project.protocols.ClientMessage();
  }

  public static com.example.p4f_project.protocols.ClientMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientMessage>
      PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
    @java.lang.Override
    public ClientMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.p4f_project.protocols.ClientMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

