// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p4f_protocols.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 opcode = 1;</code>
   * @return The opcode.
   */
  int getOpcode();

  /**
   * <code>.p4f_protocols.LoginInfo account = 2;</code>
   * @return Whether the account field is set.
   */
  boolean hasAccount();
  /**
   * <code>.p4f_protocols.LoginInfo account = 2;</code>
   * @return The account.
   */
  com.p2p.p4f.protocols.LoginInfo getAccount();
  /**
   * <code>.p4f_protocols.LoginInfo account = 2;</code>
   */
  com.p2p.p4f.protocols.LoginInfoOrBuilder getAccountOrBuilder();

  public com.p2p.p4f.protocols.ClientMessage.ClientRequestsCase getClientRequestsCase();
}
