// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.p4f_project.protocols;

/**
 * Protobuf type {@code p4f_protocols.Food}
 */
public final class Food extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:p4f_protocols.Food)
    FoodOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Food.newBuilder() to construct.
  private Food(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Food() {
    foodID_ = "";
    des_ = "";
    foodName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Food();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Food(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            foodID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            des_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            foodName_ = s;
            break;
          }
          case 32: {

            price_ = input.readInt32();
            break;
          }
          case 40: {

            amount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_Food_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_Food_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.p4f_project.protocols.Food.class, com.example.p4f_project.protocols.Food.Builder.class);
  }

  private int bitField0_;
  public static final int FOODID_FIELD_NUMBER = 1;
  private volatile java.lang.Object foodID_;
  /**
   * <code>string foodID = 1;</code>
   * @return The foodID.
   */
  @java.lang.Override
  public java.lang.String getFoodID() {
    java.lang.Object ref = foodID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foodID_ = s;
      return s;
    }
  }
  /**
   * <code>string foodID = 1;</code>
   * @return The bytes for foodID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFoodIDBytes() {
    java.lang.Object ref = foodID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      foodID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DES_FIELD_NUMBER = 2;
  private volatile java.lang.Object des_;
  /**
   * <pre>
   *description
   * </pre>
   *
   * <code>optional string des = 2;</code>
   * @return Whether the des field is set.
   */
  @java.lang.Override
  public boolean hasDes() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *description
   * </pre>
   *
   * <code>optional string des = 2;</code>
   * @return The des.
   */
  @java.lang.Override
  public java.lang.String getDes() {
    java.lang.Object ref = des_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      des_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *description
   * </pre>
   *
   * <code>optional string des = 2;</code>
   * @return The bytes for des.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDesBytes() {
    java.lang.Object ref = des_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      des_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOODNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object foodName_;
  /**
   * <code>optional string foodName = 3;</code>
   * @return Whether the foodName field is set.
   */
  @java.lang.Override
  public boolean hasFoodName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string foodName = 3;</code>
   * @return The foodName.
   */
  @java.lang.Override
  public java.lang.String getFoodName() {
    java.lang.Object ref = foodName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foodName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string foodName = 3;</code>
   * @return The bytes for foodName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFoodNameBytes() {
    java.lang.Object ref = foodName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      foodName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 4;
  private int price_;
  /**
   * <code>int32 price = 4;</code>
   * @return The price.
   */
  @java.lang.Override
  public int getPrice() {
    return price_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 5;
  private int amount_;
  /**
   * <code>int32 amount = 5;</code>
   * @return The amount.
   */
  @java.lang.Override
  public int getAmount() {
    return amount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFoodIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, foodID_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, des_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, foodName_);
    }
    if (price_ != 0) {
      output.writeInt32(4, price_);
    }
    if (amount_ != 0) {
      output.writeInt32(5, amount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFoodIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, foodID_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, des_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, foodName_);
    }
    if (price_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, price_);
    }
    if (amount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, amount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.p4f_project.protocols.Food)) {
      return super.equals(obj);
    }
    com.example.p4f_project.protocols.Food other = (com.example.p4f_project.protocols.Food) obj;

    if (!getFoodID()
        .equals(other.getFoodID())) return false;
    if (hasDes() != other.hasDes()) return false;
    if (hasDes()) {
      if (!getDes()
          .equals(other.getDes())) return false;
    }
    if (hasFoodName() != other.hasFoodName()) return false;
    if (hasFoodName()) {
      if (!getFoodName()
          .equals(other.getFoodName())) return false;
    }
    if (getPrice()
        != other.getPrice()) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FOODID_FIELD_NUMBER;
    hash = (53 * hash) + getFoodID().hashCode();
    if (hasDes()) {
      hash = (37 * hash) + DES_FIELD_NUMBER;
      hash = (53 * hash) + getDes().hashCode();
    }
    if (hasFoodName()) {
      hash = (37 * hash) + FOODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFoodName().hashCode();
    }
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.p4f_project.protocols.Food parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.Food parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.p4f_project.protocols.Food parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.p4f_project.protocols.Food parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.p4f_project.protocols.Food prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code p4f_protocols.Food}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:p4f_protocols.Food)
      com.example.p4f_project.protocols.FoodOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_Food_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_Food_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.p4f_project.protocols.Food.class, com.example.p4f_project.protocols.Food.Builder.class);
    }

    // Construct using com.example.p4f_project.protocols.Food.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      foodID_ = "";

      des_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      foodName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      price_ = 0;

      amount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.p4f_project.protocols.MessageWrapper.internal_static_p4f_protocols_Food_descriptor;
    }

    @java.lang.Override
    public com.example.p4f_project.protocols.Food getDefaultInstanceForType() {
      return com.example.p4f_project.protocols.Food.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.p4f_project.protocols.Food build() {
      com.example.p4f_project.protocols.Food result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.p4f_project.protocols.Food buildPartial() {
      com.example.p4f_project.protocols.Food result = new com.example.p4f_project.protocols.Food(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.foodID_ = foodID_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.des_ = des_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.foodName_ = foodName_;
      result.price_ = price_;
      result.amount_ = amount_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.p4f_project.protocols.Food) {
        return mergeFrom((com.example.p4f_project.protocols.Food)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.p4f_project.protocols.Food other) {
      if (other == com.example.p4f_project.protocols.Food.getDefaultInstance()) return this;
      if (!other.getFoodID().isEmpty()) {
        foodID_ = other.foodID_;
        onChanged();
      }
      if (other.hasDes()) {
        bitField0_ |= 0x00000001;
        des_ = other.des_;
        onChanged();
      }
      if (other.hasFoodName()) {
        bitField0_ |= 0x00000002;
        foodName_ = other.foodName_;
        onChanged();
      }
      if (other.getPrice() != 0) {
        setPrice(other.getPrice());
      }
      if (other.getAmount() != 0) {
        setAmount(other.getAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.p4f_project.protocols.Food parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.p4f_project.protocols.Food) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object foodID_ = "";
    /**
     * <code>string foodID = 1;</code>
     * @return The foodID.
     */
    public java.lang.String getFoodID() {
      java.lang.Object ref = foodID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foodID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string foodID = 1;</code>
     * @return The bytes for foodID.
     */
    public com.google.protobuf.ByteString
        getFoodIDBytes() {
      java.lang.Object ref = foodID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foodID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string foodID = 1;</code>
     * @param value The foodID to set.
     * @return This builder for chaining.
     */
    public Builder setFoodID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      foodID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string foodID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoodID() {
      
      foodID_ = getDefaultInstance().getFoodID();
      onChanged();
      return this;
    }
    /**
     * <code>string foodID = 1;</code>
     * @param value The bytes for foodID to set.
     * @return This builder for chaining.
     */
    public Builder setFoodIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      foodID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object des_ = "";
    /**
     * <pre>
     *description
     * </pre>
     *
     * <code>optional string des = 2;</code>
     * @return Whether the des field is set.
     */
    public boolean hasDes() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *description
     * </pre>
     *
     * <code>optional string des = 2;</code>
     * @return The des.
     */
    public java.lang.String getDes() {
      java.lang.Object ref = des_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        des_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *description
     * </pre>
     *
     * <code>optional string des = 2;</code>
     * @return The bytes for des.
     */
    public com.google.protobuf.ByteString
        getDesBytes() {
      java.lang.Object ref = des_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        des_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *description
     * </pre>
     *
     * <code>optional string des = 2;</code>
     * @param value The des to set.
     * @return This builder for chaining.
     */
    public Builder setDes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      des_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *description
     * </pre>
     *
     * <code>optional string des = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDes() {
      bitField0_ = (bitField0_ & ~0x00000001);
      des_ = getDefaultInstance().getDes();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *description
     * </pre>
     *
     * <code>optional string des = 2;</code>
     * @param value The bytes for des to set.
     * @return This builder for chaining.
     */
    public Builder setDesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      des_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object foodName_ = "";
    /**
     * <code>optional string foodName = 3;</code>
     * @return Whether the foodName field is set.
     */
    public boolean hasFoodName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string foodName = 3;</code>
     * @return The foodName.
     */
    public java.lang.String getFoodName() {
      java.lang.Object ref = foodName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foodName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string foodName = 3;</code>
     * @return The bytes for foodName.
     */
    public com.google.protobuf.ByteString
        getFoodNameBytes() {
      java.lang.Object ref = foodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string foodName = 3;</code>
     * @param value The foodName to set.
     * @return This builder for chaining.
     */
    public Builder setFoodName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      foodName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string foodName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoodName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      foodName_ = getDefaultInstance().getFoodName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string foodName = 3;</code>
     * @param value The bytes for foodName to set.
     * @return This builder for chaining.
     */
    public Builder setFoodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      foodName_ = value;
      onChanged();
      return this;
    }

    private int price_ ;
    /**
     * <code>int32 price = 4;</code>
     * @return The price.
     */
    @java.lang.Override
    public int getPrice() {
      return price_;
    }
    /**
     * <code>int32 price = 4;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(int value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 price = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0;
      onChanged();
      return this;
    }

    private int amount_ ;
    /**
     * <code>int32 amount = 5;</code>
     * @return The amount.
     */
    @java.lang.Override
    public int getAmount() {
      return amount_;
    }
    /**
     * <code>int32 amount = 5;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(int value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 amount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      
      amount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:p4f_protocols.Food)
  }

  // @@protoc_insertion_point(class_scope:p4f_protocols.Food)
  private static final com.example.p4f_project.protocols.Food DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.p4f_project.protocols.Food();
  }

  public static com.example.p4f_project.protocols.Food getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Food>
      PARSER = new com.google.protobuf.AbstractParser<Food>() {
    @java.lang.Override
    public Food parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Food(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Food> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Food> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.p4f_project.protocols.Food getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

