// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.p4f_project.protocols;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p4f_protocols.InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *re:
   *- Login: 0 = Success as customer, 1 = User does not exist, 2 = Wrong password, 3 = Success as staff
   * </pre>
   *
   * <code>int32 reCode = 1;</code>
   * @return The reCode.
   */
  int getReCode();

  /**
   * <code>.p4f_protocols.UserAccount userInfo = 2;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>.p4f_protocols.UserAccount userInfo = 2;</code>
   * @return The userInfo.
   */
  com.example.p4f_project.protocols.UserAccount getUserInfo();
  /**
   * <code>.p4f_protocols.UserAccount userInfo = 2;</code>
   */
  com.example.p4f_project.protocols.UserAccountOrBuilder getUserInfoOrBuilder();
}
