// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p4f_protocols.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Result code
   * </pre>
   *
   * <code>int32 reCode = 1;</code>
   * @return The reCode.
   */
  int getReCode();

  /**
   * <code>.p4f_protocols.UserAccount userInfo = 2;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>.p4f_protocols.UserAccount userInfo = 2;</code>
   * @return The userInfo.
   */
  com.p2p.p4f.protocols.UserAccount getUserInfo();
  /**
   * <code>.p4f_protocols.UserAccount userInfo = 2;</code>
   */
  com.p2p.p4f.protocols.UserAccountOrBuilder getUserInfoOrBuilder();
}
