// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.p4f_project.protocols;

public interface RegisterInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p4f_protocols.RegisterInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string fullname = 3;</code>
   * @return The fullname.
   */
  java.lang.String getFullname();
  /**
   * <code>string fullname = 3;</code>
   * @return The bytes for fullname.
   */
  com.google.protobuf.ByteString
      getFullnameBytes();

  /**
   * <code>string phone = 4;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 4;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string address = 5;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
