// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.p2p.p4f.protocols;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p4f_protocols.ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 opcode = 1;</code>
   * @return The opcode.
   */
  int getOpcode();

  /**
   * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
   * @return Whether the infoResponse field is set.
   */
  boolean hasInfoResponse();
  /**
   * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
   * @return The infoResponse.
   */
  com.p2p.p4f.protocols.InfoResponse getInfoResponse();
  /**
   * <code>.p4f_protocols.InfoResponse infoResponse = 2;</code>
   */
  com.p2p.p4f.protocols.InfoResponseOrBuilder getInfoResponseOrBuilder();

  public com.p2p.p4f.protocols.ServerMessage.ServerResponsesCase getServerResponsesCase();
}
